ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_kind_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_target_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_quote_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD COLUMN "target_note_id" uuid;--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_target_note_owner_fk" FOREIGN KEY ("target_note_id","user_id") REFERENCES "public"."l3_study_notes"("id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_l3_study_note_references_user_target_note" ON "l3_study_note_references" USING btree ("user_id","target_note_id","note_id");--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_no_self_note_check" CHECK (target_note_id IS NULL OR target_note_id <> note_id);--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_kind_check" CHECK (kind = ANY (ARRAY['source'::text, 'source_quote'::text, 'question'::text, 'stem_quote'::text, 'option_quote'::text, 'assessment'::text, 'note'::text]));--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_target_check" CHECK ((kind = ANY (ARRAY['source'::text, 'source_quote'::text]) AND source_id IS NOT NULL AND question_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL) OR (kind = ANY (ARRAY['question'::text, 'stem_quote'::text, 'option_quote'::text]) AND question_id IS NOT NULL AND source_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL) OR (kind = 'assessment'::text AND question_id IS NOT NULL AND assessment_id IS NOT NULL AND source_id IS NULL AND target_note_id IS NULL) OR (kind = 'note'::text AND target_note_id IS NOT NULL AND source_id IS NULL AND question_id IS NULL AND assessment_id IS NULL));--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_quote_check" CHECK ((kind = ANY (ARRAY['source_quote'::text, 'stem_quote'::text, 'option_quote'::text]) AND start_offset IS NOT NULL AND end_offset IS NOT NULL AND quote_snapshot IS NOT NULL) OR (kind = ANY (ARRAY['source'::text, 'question'::text, 'assessment'::text, 'note'::text]) AND start_offset IS NULL AND end_offset IS NULL AND quote_snapshot IS NULL));