ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_kind_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_target_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" DROP CONSTRAINT "l3_study_note_references_quote_check";--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD COLUMN "submission_id" uuid;--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD COLUMN "submission_revision_no" integer;--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD COLUMN "attempt_id" uuid;--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_submission_owner_fk" FOREIGN KEY ("submission_id","user_id") REFERENCES "public"."l3_submissions"("id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_attempt_owner_fk" FOREIGN KEY ("attempt_id","user_id") REFERENCES "public"."l3_question_attempts"("id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_l3_study_note_references_user_submission" ON "l3_study_note_references" USING btree ("user_id","submission_id","note_id");--> statement-breakpoint
CREATE INDEX "idx_l3_study_note_references_user_attempt" ON "l3_study_note_references" USING btree ("user_id","attempt_id","note_id");--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_revision_no_check" CHECK (submission_revision_no IS NULL OR submission_revision_no > 0);--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_kind_check" CHECK (kind = ANY (ARRAY['source'::text, 'source_quote'::text, 'question'::text, 'stem_quote'::text, 'option_quote'::text, 'assessment'::text, 'note'::text, 'sheet'::text, 'attempt'::text]));--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_target_check" CHECK ((kind = ANY (ARRAY['source'::text, 'source_quote'::text]) AND source_id IS NOT NULL AND question_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL AND submission_id IS NULL AND attempt_id IS NULL) OR (kind = ANY (ARRAY['question'::text, 'stem_quote'::text, 'option_quote'::text]) AND question_id IS NOT NULL AND source_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL AND submission_id IS NULL AND attempt_id IS NULL) OR (kind = 'assessment'::text AND question_id IS NOT NULL AND assessment_id IS NOT NULL AND source_id IS NULL AND target_note_id IS NULL AND submission_id IS NULL AND attempt_id IS NULL) OR (kind = 'note'::text AND target_note_id IS NOT NULL AND source_id IS NULL AND question_id IS NULL AND assessment_id IS NULL AND submission_id IS NULL AND attempt_id IS NULL) OR (kind = 'sheet'::text AND submission_id IS NOT NULL AND source_id IS NULL AND question_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL AND attempt_id IS NULL) OR (kind = 'attempt'::text AND attempt_id IS NOT NULL AND source_id IS NULL AND question_id IS NULL AND assessment_id IS NULL AND target_note_id IS NULL AND submission_id IS NULL));--> statement-breakpoint
ALTER TABLE "l3_study_note_references" ADD CONSTRAINT "l3_study_note_references_quote_check" CHECK ((kind = ANY (ARRAY['source_quote'::text, 'stem_quote'::text, 'option_quote'::text]) AND start_offset IS NOT NULL AND end_offset IS NOT NULL AND quote_snapshot IS NOT NULL) OR (kind = ANY (ARRAY['source'::text, 'question'::text, 'assessment'::text, 'note'::text, 'sheet'::text, 'attempt'::text]) AND start_offset IS NULL AND end_offset IS NULL AND quote_snapshot IS NULL));