/**
 * Schema-drift gate for the PostgreSQL full-text search vector.
 *
 * The words.search_vector column (tsvector, GENERATED ALWAYS AS) and the
 * idx_words_search GIN index are regenerated by drizzle-kit from src/db/schema.ts.
 * A careless edit to the search expression or index would silently change the
 * generated migration and break full-text search in production. This gate
 * regenerates the schema into a throwaway directory, extracts those two
 * definitions, and fails closed if they drift from the authoritative contract.
 *
 * Run: npm run db:schema:drift   (requires DATABASE_URL to be set; the value is
 * only read by drizzle-kit config loading — `generate` does not connect to a DB)
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync, readdirSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");

/** Authoritative generated SQL for the words.search_vector column. */
export const AUTHORITATIVE_SEARCH_VECTOR =
  `"search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ((((((((((COALESCE(lemma, ''::text) || ' '::text) || COALESCE(title, ''::text)) || ' '::text) || COALESCE(short_definition, ''::text)) || ' '::text) || COALESCE(definition_md, ''::text)) || ' '::text) || COALESCE((metadata ->> 'semantic_field'::text), ''::text)) || ' '::text) || COALESCE((metadata ->> 'word_freq'::text), ''::text))))) STORED`;

/** Authoritative generated SQL for the words.idx_words_search GIN index. */
export const AUTHORITATIVE_SEARCH_INDEX =
  `CREATE INDEX "idx_words_search" ON "words" USING gin ("search_vector" tsvector_ops)`;

/** Collapse whitespace and drop trailing statement punctuation for stable comparison. */
export function normalizeSql(sql: string): string {
  return sql
    .replace(/\s+/g, " ")
    .replace(/;\s*$/, "")
    .replace(/,\s*$/, "")
    .trim();
}

/** Extract the words.search_vector column definition from generated DDL, or null. */
export function extractSearchVectorColumnSql(sql: string): string | null {
  const m = sql.match(/"search_vector"[\s\S]*?STORED,?/);
  return m ? m[0] : null;
}

/** Extract the words.idx_words_search index definition from generated DDL, or null. */
export function extractSearchIndexSql(sql: string): string | null {
  const m = sql.match(/CREATE INDEX "idx_words_search"[\s\S]*?;/);
  return m ? m[0] : null;
}

export interface DriftResult {
  ok: boolean;
  columnMatch: boolean;
  indexMatch: boolean;
  detail: string;
}

/** Compare regenerated DDL against the authoritative full-text contract. */
export function compareSearchVectorContract(generatedSql: string): DriftResult {
  const col = extractSearchVectorColumnSql(generatedSql);
  const idx = extractSearchIndexSql(generatedSql);
  const columnMatch = col != null && normalizeSql(col) === normalizeSql(AUTHORITATIVE_SEARCH_VECTOR);
  const indexMatch = idx != null && normalizeSql(idx) === normalizeSql(AUTHORITATIVE_SEARCH_INDEX);
  const ok = columnMatch && indexMatch;

  const problems: string[] = [];
  if (col == null) problems.push("search_vector column not found");
  else if (!columnMatch) problems.push("search_vector column drifted from authoritative contract");
  if (idx == null) problems.push("idx_words_search index not found");
  else if (!indexMatch) problems.push("idx_words_search index drifted from authoritative contract");

  return {
    ok,
    columnMatch,
    indexMatch,
    detail: ok
      ? "search_vector column and idx_words_search index match authoritative contract"
      : problems.join("; "),
  };
}

async function runDriftCheck(): Promise<void> {
  const tmp = mkdtempSync(path.join(tmpdir(), "drift-"));
  const outDir = path.join(tmp, "out");
  const configPath = path.join(projectRoot, ".drift-check.config.ts");
  const databaseUrl = process.env.DATABASE_URL ?? "postgresql://localhost:5432/placeholder";

  try {
    const config = `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: ${JSON.stringify(outDir)},
  migrations: { schema: "vocab_migrations", table: "__v2_release_migrations" },
  dbCredentials: { url: ${JSON.stringify(databaseUrl)} },
  schemaFilter: ["public"],
  tablesFilter: ["*"],
  verbose: false,
  strict: true,
});
`;
    writeFileSync(configPath, config, "utf8");

    const binPath = path.join(projectRoot, "node_modules", "drizzle-kit", "bin.cjs");
    const res = spawnSync(process.execPath, [binPath, "generate", "--config", configPath], {
      cwd: projectRoot,
      env: { ...process.env, DATABASE_URL: databaseUrl },
      encoding: "utf8",
    });

    if (res.status !== 0) {
      const errOut = (res.stderr || res.stdout || "").trim();
      throw new Error(`drizzle-kit generate failed (exit ${res.status}): ${errOut}`);
    }

    const files = readdirSync(outDir).filter((f) => f.endsWith(".sql"));
    if (files.length === 0) throw new Error("drizzle-kit generated no SQL files");
    const sql = files.map((f) => readFileSync(path.join(outDir, f), "utf8")).join("\n");

    const result = compareSearchVectorContract(sql);
    if (!result.ok) {
      throw new Error(`Schema drift detected: ${result.detail}`);
    }
    console.log(`[schema-drift] OK — ${result.detail}`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
    if (existsSync(configPath)) rmSync(configPath, { force: true });
  }
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  runDriftCheck()
    .then(() => process.exit(0))
    .catch((e) => {
      console.error(`[schema-drift] FAILED: ${e instanceof Error ? e.message : String(e)}`);
      process.exit(1);
    });
}
