/**
 * Schema-drift gate for the PostgreSQL full-text search vector.
 *
 * The words.search_vector column (tsvector, GENERATED ALWAYS AS) and the
 * idx_words_search GIN index are regenerated by drizzle-kit from src/db/schema.ts.
 * A careless edit to the search expression or index would silently change the
 * generated migration and break full-text search in production. This gate
 * regenerates the schema into a throwaway directory, extracts those two
 * definitions, and fails closed if they drift from the authoritative contract.
 *
 * It also carries the release migration-chain guards (0047–0050 incident):
 * `_journal.json` inspection (strictly increasing `when`, complete entries,
 * no orphan tag/file in either direction) plus a generate no-op proof
 * against a throwaway copy of drizzle-release. Rationale: the drizzle migrator
 * reads `lastDbMigration` once (highest created_at) and filters with a strict
 * `<` (node_modules/drizzle-orm/pg-core/dialect.js:56-71), so tied `when`
 * values silently skip every tied migration on incremental databases; and a
 * missing terminal snapshot makes `db:generate` replay applied migrations as a
 * brand-new pseudo migration.
 *
 * Run: npm run db:schema:drift   (requires DATABASE_URL to be set; the value is
 * only read by drizzle-kit config loading — `generate` does not connect to a DB)
 */
import { spawnSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, rmSync, symlinkSync, unlinkSync, writeFileSync, readdirSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");

/** Authoritative generated SQL for the words.search_vector column. */
export const AUTHORITATIVE_SEARCH_VECTOR =
  `"search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ((((((((((COALESCE(lemma, ''::text) || ' '::text) || COALESCE(title, ''::text)) || ' '::text) || COALESCE(short_definition, ''::text)) || ' '::text) || COALESCE(definition_md, ''::text)) || ' '::text) || COALESCE((metadata ->> 'semantic_field'::text), ''::text)) || ' '::text) || COALESCE((metadata ->> 'word_freq'::text), ''::text))))) STORED`;

/** Authoritative generated SQL for the words.idx_words_search GIN index. */
export const AUTHORITATIVE_SEARCH_INDEX =
  `CREATE INDEX "idx_words_search" ON "words" USING gin ("search_vector" tsvector_ops)`;

/** Authoritative generated RLS contracts for owner-scoped rows. */
export const AUTHORITATIVE_L2_PROGRESS_RLS =
  `ALTER TABLE "user_word_l2_progress" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_L2_PROGRESS_POLICY =
  `CREATE POLICY "user_word_l2_progress_own_all" ON "user_word_l2_progress" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;
export const AUTHORITATIVE_PROFILES_SELECT_POLICY =
  `CREATE POLICY "profiles_select_own" ON "profiles" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id))`;
export const AUTHORITATIVE_HIGHLIGHTS_RLS =
  `ALTER TABLE "word_highlights" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_HIGHLIGHTS_POLICY =
  `CREATE POLICY "word_highlights_own_all" ON "word_highlights" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;
export const AUTHORITATIVE_ANNOTATIONS_RLS =
  `ALTER TABLE "word_annotations" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_ANNOTATIONS_POLICY =
  `CREATE POLICY "word_annotations_own_all" ON "word_annotations" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;

/**
 * 0039（N1 学习笔记）五张表的 owner RLS 契约——regenerate 时逐条比对，
 * 防止保存/引用路径的隔离面被静默改动。
 */
export const AUTHORITATIVE_STUDY_NOTES_RLS_CONTRACTS = [
  `ALTER TABLE "l3_study_notes" ENABLE ROW LEVEL SECURITY`,
  `CREATE POLICY "l3_study_notes_own_all" ON "l3_study_notes" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`,
  `ALTER TABLE "l3_study_note_venues" ENABLE ROW LEVEL SECURITY`,
  `CREATE POLICY "l3_study_note_venues_own_all" ON "l3_study_note_venues" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`,
  `ALTER TABLE "l3_study_topics" ENABLE ROW LEVEL SECURITY`,
  `CREATE POLICY "l3_study_topics_own_all" ON "l3_study_topics" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`,
  `ALTER TABLE "l3_study_topic_notes" ENABLE ROW LEVEL SECURITY`,
  `CREATE POLICY "l3_study_topic_notes_own_all" ON "l3_study_topic_notes" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`,
  `ALTER TABLE "l3_study_note_references" ENABLE ROW LEVEL SECURITY`,
  `CREATE POLICY "l3_study_note_references_own_all" ON "l3_study_note_references" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`,
] as const;

const REFRESH_L2_CACHE_FUNCTION_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.refresh_l2_cache(p_word_id uuid)",
  "RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); BEGIN IF v_actor_id IS NULL OR NOT EXISTS ( SELECT 1 FROM public.user_word_l2_progress AS progress WHERE progress.user_id = v_actor_id AND progress.word_id = p_word_id ) THEN RAISE EXCEPTION 'actor cannot refresh L2 cache for word' USING ERRCODE = '42501'; END IF; WITH expanded",
  "FROM public.word_l2_content AS content",
  "WHERE content.word_id = p_word_id AND content.is_active = true",
  "UPDATE public.words AS word",
  "SET collocations = aggregated.collocations, corpus_items = aggregated.corpus_items, synonym_items = aggregated.synonym_items, antonym_items = aggregated.antonym_items",
  "WHERE word.id = p_word_id",
  "ALTER FUNCTION public.refresh_l2_cache(uuid) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.refresh_l2_cache(uuid) FROM PUBLIC",
] as const;

const FINALIZE_L2_HASH_FUNCTION_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.finalize_l2_content_hash(p_word_id uuid, p_new_l2_hash text, p_new_content_hash text)",
  "RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); v_updated_count integer; BEGIN IF v_actor_id IS NULL OR NOT EXISTS ( SELECT 1 FROM public.user_word_l2_progress AS progress WHERE progress.user_id = v_actor_id AND progress.word_id = p_word_id ) THEN RAISE EXCEPTION 'actor cannot finalize L2 content hash for word' USING ERRCODE = '42501'; END IF",
  "IF p_new_l2_hash !~ '^[0-9a-f]{64}$' OR p_new_content_hash !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid content hash'",
  "FROM public.words AS word",
  "WHERE word.id = p_word_id AND word.is_deleted = false AND word.is_published = true",
  "FROM public.word_l2_content AS content WHERE content.word_id = word.id AND content.is_active = true",
  "FOR UPDATE",
  "SET l2_content_hash = p_new_l2_hash, content_hash = p_new_content_hash, updated_at = pg_catalog.now()",
  "UPDATE public.user_word_l2_progress",
  "SET l2_content_hash_snapshot = p_new_l2_hash, l2_due_at = pg_catalog.now()",
  "WHERE word_id = p_word_id AND l2_content_hash_snapshot IS NOT NULL AND l2_content_hash_snapshot <> p_new_l2_hash AND l2_paused = false",
  "GET DIAGNOSTICS v_updated_count = ROW_COUNT",
  "RETURN v_updated_count",
  "ALTER FUNCTION public.finalize_l2_content_hash(uuid, text, text) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.finalize_l2_content_hash(uuid, text, text) FROM PUBLIC",
] as const;

/**
 * 0018 override contracts — Phase G candidate pool supports "content-first"
 * (adopt candidates for words not yet in any L2 track), so the per-word
 * L2-progress requirement is dropped; an authenticated actor still required.
 */
const REFRESH_L2_CACHE_OVERRIDE_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.refresh_l2_cache(p_word_id uuid)",
  "RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); BEGIN IF v_actor_id IS NULL THEN RAISE EXCEPTION 'actor cannot refresh L2 cache for word' USING ERRCODE = '42501'; END IF; WITH expanded",
  "FROM public.word_l2_content AS content",
  "WHERE content.word_id = p_word_id AND content.is_active = true",
  "UPDATE public.words AS word",
  "SET collocations = aggregated.collocations, corpus_items = aggregated.corpus_items, synonym_items = aggregated.synonym_items, antonym_items = aggregated.antonym_items",
  "WHERE word.id = p_word_id",
  "ALTER FUNCTION public.refresh_l2_cache(uuid) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.refresh_l2_cache(uuid) FROM PUBLIC",
] as const;

const FINALIZE_L2_HASH_OVERRIDE_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.finalize_l2_content_hash(p_word_id uuid, p_new_l2_hash text, p_new_content_hash text)",
  "RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); v_updated_count integer; BEGIN IF v_actor_id IS NULL THEN RAISE EXCEPTION 'actor cannot finalize L2 content hash for word' USING ERRCODE = '42501'; END IF",
  "IF p_new_l2_hash !~ '^[0-9a-f]{64}$' OR p_new_content_hash !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid content hash'",
  "FROM public.words AS word",
  "WHERE word.id = p_word_id AND word.is_deleted = false AND word.is_published = true",
  "FROM public.word_l2_content AS content WHERE content.word_id = word.id AND content.is_active = true",
  "FOR UPDATE",
  "SET l2_content_hash = p_new_l2_hash, content_hash = p_new_content_hash, updated_at = pg_catalog.now()",
  "UPDATE public.user_word_l2_progress",
  "SET l2_content_hash_snapshot = p_new_l2_hash, l2_due_at = pg_catalog.now()",
  "WHERE word_id = p_word_id AND l2_content_hash_snapshot IS NOT NULL AND l2_content_hash_snapshot <> p_new_l2_hash AND l2_paused = false",
  "GET DIAGNOSTICS v_updated_count = ROW_COUNT",
  "RETURN v_updated_count",
  "ALTER FUNCTION public.finalize_l2_content_hash(uuid, text, text) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.finalize_l2_content_hash(uuid, text, text) FROM PUBLIC",
] as const;

/**
 * 0027 override contract (ADR-0017): refresh_l2_cache keeps the 0018 relaxed
 * authenticated-actor guard AND preserves a per-item `direction` key while
 * aggregating active rows. Losing the direction key reverts the cache to the
 * pre-ADR-0017 shape; regressing to the strict per-word progress guard is also
 * rejected (the strict marker is asserted absent below).
 */
const REFRESH_L2_CACHE_DIRECTION_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.refresh_l2_cache(p_word_id uuid)",
  "RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); BEGIN IF v_actor_id IS NULL THEN RAISE EXCEPTION 'actor cannot refresh L2 cache for word' USING ERRCODE = '42501'; END IF",
  "FROM public.word_l2_content AS content",
  "WHERE content.word_id = p_word_id AND content.is_active = true",
  "pg_catalog.jsonb_build_object('direction', content.direction)",
  "UPDATE public.words AS word",
  "SET collocations = aggregated.collocations, corpus_items = aggregated.corpus_items, synonym_items = aggregated.synonym_items, antonym_items = aggregated.antonym_items",
  "WHERE word.id = p_word_id",
  "ALTER FUNCTION public.refresh_l2_cache(uuid) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.refresh_l2_cache(uuid) FROM PUBLIC",
] as const;

/** Marker that only exists in the pre-0018 strict per-word guard. */
const STRICT_REFRESH_GUARD_MARKER = "progress.user_id = v_actor_id AND progress.word_id = p_word_id";

/** Collapse whitespace and drop trailing statement punctuation for stable comparison. */
export function normalizeSql(sql: string): string {
  return sql
    .replace(/\s+/g, " ")
    .replace(/;\s*$/, "")
    .replace(/,\s*$/, "")
    .trim();
}

/** Extract the words.search_vector column definition from generated DDL, or null. */
export function extractSearchVectorColumnSql(sql: string): string | null {
  const m = sql.match(/"search_vector"[\s\S]*?STORED,?/);
  return m ? m[0] : null;
}

/** Extract the words.idx_words_search index definition from generated DDL, or null. */
export function extractSearchIndexSql(sql: string): string | null {
  const m = sql.match(/CREATE INDEX "idx_words_search"[\s\S]*?;/);
  return m ? m[0] : null;
}

/** Compare regenerated DDL against the authoritative L2 progress RLS contract. */
export function compareL2ProgressRlsContract(generatedSql: string): boolean {
  const normalized = normalizeSql(generatedSql);
  return normalized.includes(normalizeSql(AUTHORITATIVE_L2_PROGRESS_RLS))
    && normalized.includes(normalizeSql(AUTHORITATIVE_L2_PROGRESS_POLICY));
}

/** Compare all owner-scoped RLS contracts emitted from src/db/schema.ts. */
export function compareOwnerRlsContract(generatedSql: string): boolean {
  const normalized = normalizeSql(generatedSql);
  return [
    AUTHORITATIVE_PROFILES_SELECT_POLICY,
    AUTHORITATIVE_HIGHLIGHTS_RLS,
    AUTHORITATIVE_HIGHLIGHTS_POLICY,
    AUTHORITATIVE_ANNOTATIONS_RLS,
    AUTHORITATIVE_ANNOTATIONS_POLICY,
    ...AUTHORITATIVE_STUDY_NOTES_RLS_CONTRACTS,
  ].every((contract) => normalized.includes(normalizeSql(contract)));
}

/** Compare hand-authored SECURITY DEFINER migration contracts (0012 baseline). */
export function compareSecurityDefinerContract(migrationSql: string): boolean {
  const normalized = normalizeSql(migrationSql);
  return [...REFRESH_L2_CACHE_FUNCTION_CONTRACT, ...FINALIZE_L2_HASH_FUNCTION_CONTRACT]
    .every((contract) => normalized.includes(normalizeSql(contract)));
}

/** Compare the 0018 relaxed-guard override (Phase G content-first candidates). */
export function compareSecurityDefinerOverrideContract(overrideSql: string): boolean {
  const normalized = normalizeSql(overrideSql);
  return [...REFRESH_L2_CACHE_OVERRIDE_CONTRACT, ...FINALIZE_L2_HASH_OVERRIDE_CONTRACT]
    .every((contract) => normalized.includes(normalizeSql(contract)));
}

/**
 * Compare the 0027 direction-preserving refresh_l2_cache override (ADR-0017).
 * Requires the relaxed guard, the per-item direction key, and rejects any
 * regression back to the pre-0018 strict per-word progress guard.
 */
export function compareSecurityDefinerDirectionContract(migrationSql: string): boolean {
  const normalized = normalizeSql(migrationSql);
  const intact = REFRESH_L2_CACHE_DIRECTION_CONTRACT
    .every((contract) => normalized.includes(normalizeSql(contract)));
  return intact && !normalized.includes(normalizeSql(STRICT_REFRESH_GUARD_MARKER));
}

/** Minimal shape of one `_journal.json` entry, kept loose for hostile input. */
export interface MigrationJournalEntry {
  idx?: unknown;
  version?: unknown;
  when?: unknown;
  tag?: unknown;
  breakpoints?: unknown;
}

/**
 * Journal invariants that `db:migrate` silently depends on:
 *
 *   ① `when` is strictly increasing (ties are skipped by the migrator's
 *      one-shot `lastDbMigration` + strict `<` comparison),
 *   ② every entry carries `version` and `breakpoints` (drizzle-kit's own
 *      `writeResult` emits both; hand-edited tails must match).
 *
 * Returns one human-readable problem per violation; empty means healthy.
 */
export function analyzeMigrationJournal(journal: unknown): string[] {
  const problems: string[] = [];
  const entries = (journal as { entries?: unknown } | null | undefined)?.entries;
  if (!Array.isArray(entries) || entries.length === 0) {
    return ["_journal.json has no entries array"];
  }

  entries.forEach((raw, index) => {
    const entry = (raw ?? {}) as MigrationJournalEntry;
    const label = typeof entry.tag === "string" && entry.tag.length > 0 ? entry.tag : `entries[${index}]`;
    if (typeof entry.tag !== "string" || entry.tag.length === 0) {
      problems.push(`${label}: tag must be a non-empty string`);
    }
    if (typeof entry.when !== "number" || !Number.isFinite(entry.when)) {
      problems.push(`${label}: when must be a finite number`);
    }
    if (typeof entry.version !== "string" || entry.version.length === 0) {
      problems.push(`${label}: missing version`);
    }
    if (typeof entry.breakpoints !== "boolean") {
      problems.push(`${label}: missing breakpoints`);
    }

    const previous = (entries[index - 1] ?? {}) as MigrationJournalEntry;
    if (
      index > 0
      && typeof entry.when === "number"
      && typeof previous.when === "number"
      && entry.when <= previous.when
    ) {
      problems.push(
        `${label}: when ${entry.when} is not strictly greater than previous entry ` +
          `(when ${previous.when}) — the migrator skips tied when values on incremental databases`,
      );
    }
  });

  return problems;
}

/**
 * Folder-level journal/`.sql` coverage:
 *
 *   ③ every journal tag resolves to `<tag>.sql`,
 *   ④ every `NNNN_*.sql` is registered in the journal (no orphans either way).
 *
 * Combined with {@link analyzeMigrationJournal} this is the full ①②③④ guard.
 */
export function verifyReleaseMigrationFolder(releaseDir: string): string[] {
  const journalPath = path.join(releaseDir, "meta", "_journal.json");
  if (!existsSync(journalPath)) {
    return [`missing migration journal: ${journalPath}`];
  }

  const journal = JSON.parse(readFileSync(journalPath, "utf8")) as { entries?: Array<{ tag?: unknown }> };
  const problems = analyzeMigrationJournal(journal);

  const tags = new Set(
    (Array.isArray(journal.entries) ? journal.entries : [])
      .map((entry) => entry?.tag)
      .filter((tag): tag is string => typeof tag === "string" && tag.length > 0),
  );
  const sqlFiles = readdirSync(releaseDir).filter((file) => /^\d{4}_.+\.sql$/.test(file));

  for (const tag of tags) {
    if (!existsSync(path.join(releaseDir, `${tag}.sql`))) {
      problems.push(`journal tag ${tag} has no matching ${tag}.sql`);
    }
  }
  for (const file of sqlFiles) {
    if (!tags.has(file.replace(/\.sql$/, ""))) {
      problems.push(`${file} has no journal entry`);
    }
  }

  return problems;
}

/** New artifact paths present in `after` but not in `before`. */
export function diffReleaseArtifacts(before: readonly string[], after: readonly string[]): string[] {
  const known = new Set(before);
  return after.filter((file) => !known.has(file)).sort();
}

/** Relative posix-style paths of every file under `dir` (recursive). */
function listArtifacts(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listArtifacts(full, base));
    else out.push(path.relative(base, full).split(path.sep).join("/"));
  }
  return out.sort();
}

export interface GenerateNoOpResult {
  ok: boolean;
  /** Migration artifacts generate would have written — empty on a clean chain. */
  added: string[];
  detail: string;
}

/**
 * Prove `drizzle-kit generate` is a no-op against the committed migration chain:
 * run it inside a throwaway sandbox (src + drizzle-release + linked
 * node_modules, `out` relative) and fail if any new `.sql`/snapshot appears.
 * A missing terminal snapshot is exactly the 0047–0050 defect — the next
 * `db:generate` then replays applied migrations as a brand-new pseudo migration.
 *
 * `generate` does not connect to a database, so this stays CI-safe without
 * Postgres; `strict` is off and stdin is ignored so a drifted chain reports
 * instead of hanging on an interactive rename/delete prompt. The sandbox (and
 * a relative `out`) is mandatory, not cosmetic: drizzle-kit joins `out` with
 * the working directory, so an absolute out path from a foreign drive resolves
 * to `<cwd>\C:\...` and aborts — printing the error yet still exiting 0. That
 * is why success additionally requires the "No schema changes" evidence on
 * stdout instead of trusting the exit code alone.
 */
export function verifyGenerateIsNoOp(
  projectRoot: string,
  databaseUrl = process.env.DATABASE_URL ?? "postgresql://localhost:5432/placeholder",
): GenerateNoOpResult {
  const tmp = mkdtempSync(path.join(tmpdir(), "release-generate-noop-"));
  const sandbox = path.join(tmp, "project");
  const outDir = path.join(sandbox, "drizzle-release");
  const configPath = path.join(sandbox, ".migration-noop.config.ts");

  try {
    mkdirSync(sandbox, { recursive: true });
    cpSync(path.join(projectRoot, "src"), path.join(sandbox, "src"), { recursive: true });
    cpSync(path.join(projectRoot, "drizzle-release"), outDir, { recursive: true });
    cpSync(path.join(projectRoot, "package.json"), path.join(sandbox, "package.json"));
    // drizzle-kit bundles the config and schema with esbuild from the sandbox;
    // a directory link keeps node_modules resolution without copying an install.
    symlinkSync(
      path.join(projectRoot, "node_modules"),
      path.join(sandbox, "node_modules"),
      process.platform === "win32" ? "junction" : "dir",
    );

    const before = listArtifacts(outDir);
    writeFileSync(
      configPath,
      `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: "./drizzle-release",
  migrations: { schema: "vocab_migrations", table: "__v2_release_migrations" },
  dbCredentials: { url: ${JSON.stringify(databaseUrl)} },
  schemaFilter: ["public"],
  tablesFilter: ["*"],
  verbose: false,
  strict: false,
});
`,
      "utf8",
    );

    const binPath = path.join(projectRoot, "node_modules", "drizzle-kit", "bin.cjs");
    const res = spawnSync(process.execPath, [binPath, "generate", "--config", configPath], {
      cwd: sandbox,
      env: { ...process.env, DATABASE_URL: databaseUrl },
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });

    const stdout = res.stdout ?? "";
    if (res.status !== 0) {
      const errOut = (res.stderr || stdout || "").trim();
      return {
        ok: false,
        added: [],
        detail: `drizzle-kit generate failed (exit ${res.status}): ${errOut}`,
      };
    }

    const added = diffReleaseArtifacts(before, listArtifacts(outDir));
    if (added.length > 0) {
      return {
        ok: false,
        added,
        detail:
          "drizzle-kit generate would write new migration artifacts " +
          `(${added.join(", ")}) — the meta snapshots drifted from src/db/schema.ts`,
      };
    }

    if (!/no schema changes/i.test(stdout)) {
      return {
        ok: false,
        added,
        detail:
          "drizzle-kit generate exited 0 without reporting \"No schema changes\" — " +
          `treating it as a failure (stderr: ${(res.stderr || "").trim() || "(empty)"})`,
      };
    }

    return { ok: true, added, detail: "drizzle-kit generate is a no-op against the committed chain" };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

export interface DriftResult {
  ok: boolean;
  columnMatch: boolean;
  indexMatch: boolean;
  l2ProgressRlsMatch: boolean;
  ownerRlsMatch: boolean;
  detail: string;
}

/** Compare regenerated DDL against the authoritative full-text contract. */
export function compareSearchVectorContract(generatedSql: string): DriftResult {
  const col = extractSearchVectorColumnSql(generatedSql);
  const idx = extractSearchIndexSql(generatedSql);
  const columnMatch = col != null && normalizeSql(col) === normalizeSql(AUTHORITATIVE_SEARCH_VECTOR);
  const indexMatch = idx != null && normalizeSql(idx) === normalizeSql(AUTHORITATIVE_SEARCH_INDEX);
  const l2ProgressRlsMatch = compareL2ProgressRlsContract(generatedSql);
  const ownerRlsMatch = compareOwnerRlsContract(generatedSql);
  const ok = columnMatch && indexMatch && l2ProgressRlsMatch && ownerRlsMatch;

  const problems: string[] = [];
  if (col == null) problems.push("search_vector column not found");
  else if (!columnMatch) problems.push("search_vector column drifted from authoritative contract");
  if (idx == null) problems.push("idx_words_search index not found");
  else if (!indexMatch) problems.push("idx_words_search index drifted from authoritative contract");
  if (!l2ProgressRlsMatch) problems.push("user_word_l2_progress owner RLS drifted from authoritative contract");
  if (!ownerRlsMatch) problems.push("profiles/highlights/annotations owner RLS drifted from authoritative contract");

  return {
    ok,
    columnMatch,
    indexMatch,
    l2ProgressRlsMatch,
    ownerRlsMatch,
    detail: ok
      ? "search vector and owner RLS policies match authoritative contracts"
      : problems.join("; "),
  };
}

async function runDriftCheck(): Promise<void> {
  const tmp = mkdtempSync(path.join(tmpdir(), "drift-"));
  const outDir = path.join(tmp, "out");
  const configPath = path.join(projectRoot, ".drift-check.config.ts");
  const databaseUrl = process.env.DATABASE_URL ?? "postgresql://localhost:5432/placeholder";

  try {
    const config = `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: ${JSON.stringify(outDir)},
  migrations: { schema: "vocab_migrations", table: "__v2_release_migrations" },
  dbCredentials: { url: ${JSON.stringify(databaseUrl)} },
  schemaFilter: ["public"],
  tablesFilter: ["*"],
  verbose: false,
  strict: true,
});
`;
    writeFileSync(configPath, config, "utf8");

    const binPath = path.join(projectRoot, "node_modules", "drizzle-kit", "bin.cjs");
    const res = spawnSync(process.execPath, [binPath, "generate", "--config", configPath], {
      cwd: projectRoot,
      env: { ...process.env, DATABASE_URL: databaseUrl },
      encoding: "utf8",
    });

    if (res.status !== 0) {
      const errOut = (res.stderr || res.stdout || "").trim();
      throw new Error(`drizzle-kit generate failed (exit ${res.status}): ${errOut}`);
    }

    const files = readdirSync(outDir).filter((f) => f.endsWith(".sql"));
    if (files.length === 0) throw new Error("drizzle-kit generated no SQL files");
    const sql = files.map((f) => readFileSync(path.join(outDir, f), "utf8")).join("\n");

    const result = compareSearchVectorContract(sql);
    if (!result.ok) {
      throw new Error(`Schema drift detected: ${result.detail}`);
    }

    const securityFunctionMigration = path.join(projectRoot, "drizzle-release", "0012_glamorous_peter_quill.sql");
    if (!existsSync(securityFunctionMigration)) {
      throw new Error("Schema drift detected: SECURITY DEFINER migration is missing");
    }
    const securityFunctionSql = readFileSync(securityFunctionMigration, "utf8");
    if (!compareSecurityDefinerContract(securityFunctionSql)) {
      throw new Error("Schema drift detected: SECURITY DEFINER function contract changed");
    }

    const securityFunctionOverride = path.join(projectRoot, "drizzle-release", "0018_witty_longhorn.sql");
    if (!existsSync(securityFunctionOverride)) {
      throw new Error("Schema drift detected: SECURITY DEFINER override migration (0018) is missing");
    }
    const overrideSql = readFileSync(securityFunctionOverride, "utf8");
    if (!compareSecurityDefinerOverrideContract(overrideSql)) {
      throw new Error("Schema drift detected: SECURITY DEFINER relaxed-guard override contract changed");
    }

    const securityFunctionDirection = path.join(projectRoot, "drizzle-release", "0027_cold_eddie_brock.sql");
    if (!existsSync(securityFunctionDirection)) {
      throw new Error("Schema drift detected: direction-preserving override migration (0027) is missing");
    }
    const directionSql = readFileSync(securityFunctionDirection, "utf8");
    if (!compareSecurityDefinerDirectionContract(directionSql)) {
      throw new Error("Schema drift detected: 0027 direction-preserving refresh_l2_cache contract changed");
    }

    const releaseDir = path.join(projectRoot, "drizzle-release");
    const chainProblems = verifyReleaseMigrationFolder(releaseDir);
    if (chainProblems.length > 0) {
      throw new Error(`Migration chain invalid: ${chainProblems.join("; ")}`);
    }

    const noOp = verifyGenerateIsNoOp(projectRoot, databaseUrl);
    if (!noOp.ok) {
      throw new Error(`Migration chain invalid: ${noOp.detail}`);
    }

    console.log(
      `[schema-drift] OK — ${result.detail}; SECURITY DEFINER functions match authoritative contracts; ` +
        `migration journal is strictly increasing with no orphan tag/file and ${noOp.detail}`,
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
    if (existsSync(configPath)) unlinkSync(configPath);
  }
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  runDriftCheck()
    .then(() => process.exit(0))
    .catch((e) => {
      console.error(`[schema-drift] FAILED: ${e instanceof Error ? e.message : String(e)}`);
      process.exit(1);
    });
}
