/**
 * Schema-drift gate for the PostgreSQL full-text search vector.
 *
 * The words.search_vector column (tsvector, GENERATED ALWAYS AS) and the
 * idx_words_search GIN index are regenerated by drizzle-kit from src/db/schema.ts.
 * A careless edit to the search expression or index would silently change the
 * generated migration and break full-text search in production. This gate
 * regenerates the schema into a throwaway directory, extracts those two
 * definitions, and fails closed if they drift from the authoritative contract.
 *
 * Run: npm run db:schema:drift   (requires DATABASE_URL to be set; the value is
 * only read by drizzle-kit config loading — `generate` does not connect to a DB)
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, unlinkSync, writeFileSync, readdirSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");

/** Authoritative generated SQL for the words.search_vector column. */
export const AUTHORITATIVE_SEARCH_VECTOR =
  `"search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ((((((((((COALESCE(lemma, ''::text) || ' '::text) || COALESCE(title, ''::text)) || ' '::text) || COALESCE(short_definition, ''::text)) || ' '::text) || COALESCE(definition_md, ''::text)) || ' '::text) || COALESCE((metadata ->> 'semantic_field'::text), ''::text)) || ' '::text) || COALESCE((metadata ->> 'word_freq'::text), ''::text))))) STORED`;

/** Authoritative generated SQL for the words.idx_words_search GIN index. */
export const AUTHORITATIVE_SEARCH_INDEX =
  `CREATE INDEX "idx_words_search" ON "words" USING gin ("search_vector" tsvector_ops)`;

/** Authoritative generated RLS contracts for owner-scoped rows. */
export const AUTHORITATIVE_L2_PROGRESS_RLS =
  `ALTER TABLE "user_word_l2_progress" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_L2_PROGRESS_POLICY =
  `CREATE POLICY "user_word_l2_progress_own_all" ON "user_word_l2_progress" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;
export const AUTHORITATIVE_PROFILES_SELECT_POLICY =
  `CREATE POLICY "profiles_select_own" ON "profiles" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id))`;
export const AUTHORITATIVE_HIGHLIGHTS_RLS =
  `ALTER TABLE "word_highlights" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_HIGHLIGHTS_POLICY =
  `CREATE POLICY "word_highlights_own_all" ON "word_highlights" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;
export const AUTHORITATIVE_ANNOTATIONS_RLS =
  `ALTER TABLE "word_annotations" ENABLE ROW LEVEL SECURITY`;
export const AUTHORITATIVE_ANNOTATIONS_POLICY =
  `CREATE POLICY "word_annotations_own_all" ON "word_annotations" AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id))`;

const REFRESH_L2_CACHE_FUNCTION_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.refresh_l2_cache(p_word_id uuid)",
  "RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); BEGIN IF v_actor_id IS NULL OR NOT EXISTS ( SELECT 1 FROM public.user_word_l2_progress AS progress WHERE progress.user_id = v_actor_id AND progress.word_id = p_word_id ) THEN RAISE EXCEPTION 'actor cannot refresh L2 cache for word' USING ERRCODE = '42501'; END IF; WITH expanded",
  "FROM public.word_l2_content AS content",
  "WHERE content.word_id = p_word_id AND content.is_active = true",
  "UPDATE public.words AS word",
  "SET collocations = aggregated.collocations, corpus_items = aggregated.corpus_items, synonym_items = aggregated.synonym_items, antonym_items = aggregated.antonym_items",
  "WHERE word.id = p_word_id",
  "ALTER FUNCTION public.refresh_l2_cache(uuid) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.refresh_l2_cache(uuid) FROM PUBLIC",
] as const;

const FINALIZE_L2_HASH_FUNCTION_CONTRACT = [
  "CREATE OR REPLACE FUNCTION public.finalize_l2_content_hash(p_word_id uuid, p_new_l2_hash text, p_new_content_hash text)",
  "RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public",
  "DECLARE v_actor_id uuid := auth.uid(); v_updated_count integer; BEGIN IF v_actor_id IS NULL OR NOT EXISTS ( SELECT 1 FROM public.user_word_l2_progress AS progress WHERE progress.user_id = v_actor_id AND progress.word_id = p_word_id ) THEN RAISE EXCEPTION 'actor cannot finalize L2 content hash for word' USING ERRCODE = '42501'; END IF",
  "IF p_new_l2_hash !~ '^[0-9a-f]{64}$' OR p_new_content_hash !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid content hash'",
  "FROM public.words AS word",
  "WHERE word.id = p_word_id AND word.is_deleted = false AND word.is_published = true",
  "FROM public.word_l2_content AS content WHERE content.word_id = word.id AND content.is_active = true",
  "FOR UPDATE",
  "SET l2_content_hash = p_new_l2_hash, content_hash = p_new_content_hash, updated_at = pg_catalog.now()",
  "UPDATE public.user_word_l2_progress",
  "SET l2_content_hash_snapshot = p_new_l2_hash, l2_due_at = pg_catalog.now()",
  "WHERE word_id = p_word_id AND l2_content_hash_snapshot IS NOT NULL AND l2_content_hash_snapshot <> p_new_l2_hash AND l2_paused = false",
  "GET DIAGNOSTICS v_updated_count = ROW_COUNT",
  "RETURN v_updated_count",
  "ALTER FUNCTION public.finalize_l2_content_hash(uuid, text, text) OWNER TO vocab_migration",
  "REVOKE ALL ON FUNCTION public.finalize_l2_content_hash(uuid, text, text) FROM PUBLIC",
] as const;

/** Collapse whitespace and drop trailing statement punctuation for stable comparison. */
export function normalizeSql(sql: string): string {
  return sql
    .replace(/\s+/g, " ")
    .replace(/;\s*$/, "")
    .replace(/,\s*$/, "")
    .trim();
}

/** Extract the words.search_vector column definition from generated DDL, or null. */
export function extractSearchVectorColumnSql(sql: string): string | null {
  const m = sql.match(/"search_vector"[\s\S]*?STORED,?/);
  return m ? m[0] : null;
}

/** Extract the words.idx_words_search index definition from generated DDL, or null. */
export function extractSearchIndexSql(sql: string): string | null {
  const m = sql.match(/CREATE INDEX "idx_words_search"[\s\S]*?;/);
  return m ? m[0] : null;
}

/** Compare regenerated DDL against the authoritative L2 progress RLS contract. */
export function compareL2ProgressRlsContract(generatedSql: string): boolean {
  const normalized = normalizeSql(generatedSql);
  return normalized.includes(normalizeSql(AUTHORITATIVE_L2_PROGRESS_RLS))
    && normalized.includes(normalizeSql(AUTHORITATIVE_L2_PROGRESS_POLICY));
}

/** Compare all owner-scoped RLS contracts emitted from src/db/schema.ts. */
export function compareOwnerRlsContract(generatedSql: string): boolean {
  const normalized = normalizeSql(generatedSql);
  return [
    AUTHORITATIVE_PROFILES_SELECT_POLICY,
    AUTHORITATIVE_HIGHLIGHTS_RLS,
    AUTHORITATIVE_HIGHLIGHTS_POLICY,
    AUTHORITATIVE_ANNOTATIONS_RLS,
    AUTHORITATIVE_ANNOTATIONS_POLICY,
  ].every((contract) => normalized.includes(normalizeSql(contract)));
}

/** Compare hand-authored SECURITY DEFINER migration contracts. */
export function compareSecurityDefinerContract(migrationSql: string): boolean {
  const normalized = normalizeSql(migrationSql);
  return [...REFRESH_L2_CACHE_FUNCTION_CONTRACT, ...FINALIZE_L2_HASH_FUNCTION_CONTRACT]
    .every((contract) => normalized.includes(normalizeSql(contract)));
}

export interface DriftResult {
  ok: boolean;
  columnMatch: boolean;
  indexMatch: boolean;
  l2ProgressRlsMatch: boolean;
  ownerRlsMatch: boolean;
  detail: string;
}

/** Compare regenerated DDL against the authoritative full-text contract. */
export function compareSearchVectorContract(generatedSql: string): DriftResult {
  const col = extractSearchVectorColumnSql(generatedSql);
  const idx = extractSearchIndexSql(generatedSql);
  const columnMatch = col != null && normalizeSql(col) === normalizeSql(AUTHORITATIVE_SEARCH_VECTOR);
  const indexMatch = idx != null && normalizeSql(idx) === normalizeSql(AUTHORITATIVE_SEARCH_INDEX);
  const l2ProgressRlsMatch = compareL2ProgressRlsContract(generatedSql);
  const ownerRlsMatch = compareOwnerRlsContract(generatedSql);
  const ok = columnMatch && indexMatch && l2ProgressRlsMatch && ownerRlsMatch;

  const problems: string[] = [];
  if (col == null) problems.push("search_vector column not found");
  else if (!columnMatch) problems.push("search_vector column drifted from authoritative contract");
  if (idx == null) problems.push("idx_words_search index not found");
  else if (!indexMatch) problems.push("idx_words_search index drifted from authoritative contract");
  if (!l2ProgressRlsMatch) problems.push("user_word_l2_progress owner RLS drifted from authoritative contract");
  if (!ownerRlsMatch) problems.push("profiles/highlights/annotations owner RLS drifted from authoritative contract");

  return {
    ok,
    columnMatch,
    indexMatch,
    l2ProgressRlsMatch,
    ownerRlsMatch,
    detail: ok
      ? "search vector and owner RLS policies match authoritative contracts"
      : problems.join("; "),
  };
}

async function runDriftCheck(): Promise<void> {
  const tmp = mkdtempSync(path.join(tmpdir(), "drift-"));
  const outDir = path.join(tmp, "out");
  const configPath = path.join(projectRoot, ".drift-check.config.ts");
  const databaseUrl = process.env.DATABASE_URL ?? "postgresql://localhost:5432/placeholder";

  try {
    const config = `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: ${JSON.stringify(outDir)},
  migrations: { schema: "vocab_migrations", table: "__v2_release_migrations" },
  dbCredentials: { url: ${JSON.stringify(databaseUrl)} },
  schemaFilter: ["public"],
  tablesFilter: ["*"],
  verbose: false,
  strict: true,
});
`;
    writeFileSync(configPath, config, "utf8");

    const binPath = path.join(projectRoot, "node_modules", "drizzle-kit", "bin.cjs");
    const res = spawnSync(process.execPath, [binPath, "generate", "--config", configPath], {
      cwd: projectRoot,
      env: { ...process.env, DATABASE_URL: databaseUrl },
      encoding: "utf8",
    });

    if (res.status !== 0) {
      const errOut = (res.stderr || res.stdout || "").trim();
      throw new Error(`drizzle-kit generate failed (exit ${res.status}): ${errOut}`);
    }

    const files = readdirSync(outDir).filter((f) => f.endsWith(".sql"));
    if (files.length === 0) throw new Error("drizzle-kit generated no SQL files");
    const sql = files.map((f) => readFileSync(path.join(outDir, f), "utf8")).join("\n");

    const result = compareSearchVectorContract(sql);
    if (!result.ok) {
      throw new Error(`Schema drift detected: ${result.detail}`);
    }

    const securityFunctionMigration = path.join(projectRoot, "drizzle-release", "0012_glamorous_peter_quill.sql");
    if (!existsSync(securityFunctionMigration)) {
      throw new Error("Schema drift detected: SECURITY DEFINER migration is missing");
    }
    const securityFunctionSql = readFileSync(securityFunctionMigration, "utf8");
    if (!compareSecurityDefinerContract(securityFunctionSql)) {
      throw new Error("Schema drift detected: SECURITY DEFINER function contract changed");
    }

    console.log(`[schema-drift] OK — ${result.detail}; SECURITY DEFINER functions match authoritative contracts`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
    if (existsSync(configPath)) unlinkSync(configPath);
  }
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  runDriftCheck()
    .then(() => process.exit(0))
    .catch((e) => {
      console.error(`[schema-drift] FAILED: ${e instanceof Error ? e.message : String(e)}`);
      process.exit(1);
    });
}
